name = "justwrite"
compatibility_date = "2024-07-01"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYjUwYjFmMzktNjY0MS00MTdlLTlhZjctZTdkMjY4MWY2MTgzIiwidGVuYW50X2lkIjoiNGNjZTc4MzJiYWEyN2U4MWY3MjgxNjgwOTAzYjg2YjAxOWNkMzlkM2U2MDVhZGE2Nzk4NjE1YTMxZmQ1YTRhOSIsImludGVybmFsX3NlY3JldCI6ImZlYjJhMjlmLWEwM2MtNDZmMi1iZTU1LTk0ZDNlYmUwMmMxYyJ9.z9kpesqtQGqgHm0WPYsn4yQUz17xnJtbOMmXAnRYTxQ"
GEMINI_API_KEY = "AIzaSyCoJgND8xluFVoHTc56kBeRAiRomGs1Lho"
JWT_SECRET = "jchwfwwe34r4gfrdrdr6547"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
